import { getRandomEnum } from 'utils';
import { ITodos, TCategory, TPriority, TStatus } from 'types';

const today = new Date();

const yesterday = new Date(today);
yesterday.setDate(yesterday.getDate() - 1);

const tomorrow = new Date(today);
tomorrow.setDate(tomorrow.getDate() + 1);

const randomFuture = new Date(today);
tomorrow.setDate(randomFuture.getDate() + Math.floor(Math.random() * 100));

export const mockData: ITodos = [
  {
    id: 1,
    text: '시작 안함1',
    status: TStatus.NOT_STARTED,
    createdAt: tomorrow,
    updatedAt: tomorrow,
    due: randomFuture,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },
  {
    id: 2,
    text: '시작 안한2',
    status: TStatus.NOT_STARTED,
    createdAt: tomorrow,
    updatedAt: tomorrow,
    due: randomFuture,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },
  {
    id: 3,
    text: '시작 안한3',
    status: TStatus.NOT_STARTED,
    createdAt: tomorrow,
    updatedAt: tomorrow,
    due: randomFuture,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },
  {
    id: 4,
    text: '시작 안한4',
    status: TStatus.NOT_STARTED,
    createdAt: tomorrow,
    updatedAt: tomorrow,
    due: randomFuture,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },
  {
    id: 5,
    text: '시작 안한5',
    status: TStatus.NOT_STARTED,
    createdAt: tomorrow,
    updatedAt: tomorrow,
    due: randomFuture,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },

  {
    id: 6,
    text: '현재 진행1',
    status: TStatus.ONGOING,
    createdAt: yesterday,
    updatedAt: yesterday,
    due: randomFuture,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },
  {
    id: 7,
    text: '현재 진행2',
    status: TStatus.ONGOING,
    createdAt: yesterday,
    updatedAt: yesterday,
    due: randomFuture,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },
  {
    id: 8,
    text: '현재 진행3',
    status: TStatus.ONGOING,
    createdAt: yesterday,
    updatedAt: yesterday,
    due: randomFuture,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },
  {
    id: 9,
    text: '현재 진행4',
    status: TStatus.ONGOING,
    createdAt: yesterday,
    updatedAt: yesterday,
    due: randomFuture,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },
  {
    id: 10,
    text: '현재 진행5',
    status: TStatus.ONGOING,
    createdAt: yesterday,
    updatedAt: yesterday,
    due: randomFuture,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },

  {
    id: 11,
    text: '완료 목표 날짜 지남1',
    status: TStatus.ONGOING,
    createdAt: yesterday,
    updatedAt: yesterday,
    due: yesterday,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },
  {
    id: 12,
    text: '완료 목표 날짜 지남2',
    status: TStatus.ONGOING,
    createdAt: yesterday,
    updatedAt: yesterday,
    due: yesterday,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },
  {
    id: 13,
    text: '완료 목표 날짜 지남3',
    status: TStatus.ONGOING,
    createdAt: yesterday,
    updatedAt: yesterday,
    due: yesterday,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },
  {
    id: 14,
    text: '완료 목표 날짜 지남4',
    status: TStatus.NOT_STARTED,
    createdAt: yesterday,
    updatedAt: yesterday,
    due: yesterday,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },
  {
    id: 15,
    text: '완료 목표 날짜 지남5',
    status: TStatus.NOT_STARTED,
    createdAt: yesterday,
    updatedAt: yesterday,
    due: yesterday,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },

  {
    id: 16,
    text: '완료1',
    status: TStatus.FINISHED,
    createdAt: yesterday,
    updatedAt: yesterday,
    due: randomFuture,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },
  {
    id: 17,
    text: '완료2',
    status: TStatus.FINISHED,
    createdAt: yesterday,
    updatedAt: yesterday,
    due: randomFuture,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },
  {
    id: 18,
    text: '완료3',
    status: TStatus.FINISHED,
    createdAt: yesterday,
    updatedAt: yesterday,
    due: randomFuture,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },
  {
    id: 19,
    text: '완료4',
    status: TStatus.FINISHED,
    createdAt: yesterday,
    updatedAt: yesterday,
    due: randomFuture,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },
  {
    id: 20,
    text: '완료5',
    status: TStatus.FINISHED,
    createdAt: yesterday,
    updatedAt: yesterday,
    due: randomFuture,
    category: getRandomEnum(TCategory),
    priority: getRandomEnum(TPriority),
  },
];
